using System.Text;

namespace ITI.TypeScriptDtoGenerator;

internal static class IndexGenerator
{
    public static void GenerateIndex(string directoryPath)
    {
        var output = new StringBuilder();
        output.AppendLine(Util.AutoGeneratedMessage);

        // Without OrderBy, exports will be in an arbitrary order on Linux
        var paths = Directory.EnumerateFiles(directoryPath, "*.ts?")
            .OrderBy(p => p.ToLowerInvariant())
            .ToArray();

        foreach (var path in paths)
        {
            if (path.Contains("index.ts")) continue;

            var noExtension = Path.GetFileNameWithoutExtension(path);
            output.AppendLine($"export * from './{noExtension}'");
        }

        Util.ConvertLineEndings(output);
        var outputPath = Path.Combine(directoryPath, "index.ts");
        File.WriteAllText(outputPath, output.ToString());
    }
}
