using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ITI.TypeScriptDtoGenerator
{
    internal static class IndexGenerator
    {
        public static void GenerateIndex(string directoryPath)
        {
            var output = new StringBuilder();
            output.AppendLine(Util.AutoGeneratedMessage);

            foreach (var path in Directory.EnumerateFiles(directoryPath, "*.ts?"))
            {
                if (path.Contains("index.ts")) continue;

                var noExtension = Path.GetFileNameWithoutExtension(path);
                output.AppendLine($"export * from './{noExtension}'");
            }

            Util.ConvertLineEndings(output);
            var outputPath = Path.Combine(directoryPath, "index.ts");
            File.WriteAllText(outputPath, output.ToString());
        }
    }
}
