using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ITI.TypeScriptDtoGenerator
{
    internal static class Util
    {
        public static readonly string AutoGeneratedMessage = "// Auto-generated by ITI.TypeScriptDtoGenerator - do not edit";
    }
}
