using System.Text;

namespace ITI.TypeScriptDtoGenerator;

internal static class Util
{
    public static readonly string AutoGeneratedMessage = "// Auto-generated by ITI.TypeScriptDtoGenerator - do not edit";

    public static void ConvertLineEndings(StringBuilder stringBuilder)
    {
        stringBuilder.Replace("\r", "");

        if (stringBuilder[^1] != '\n')
        {
            stringBuilder.Append('\n');
        }
    }
}
