using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ITI.TypeScriptDtoGenerator
{
    internal class Util
    {
        public static readonly string AutoGeneratedMessage = "// Auto-generated by ITI.TypeScriptDtoGenerator - do not edit";

        public static void ConvertLineEndings(StringBuilder stringBuilder)
        {
            stringBuilder.Replace("\r", "");

            if (!stringBuilder.ToString().EndsWith("\n"))
            {
                stringBuilder.AppendLine("\n");
            }
            return;
        }
    }
}
